### PR TITLE
upgrade to the latest buildpack

### PR DESCRIPTION
**Pull request by duanhongyi**

### CODE REVIEW

**Comment by Cryptophobia** [comment]
Hi @duanhongyi , thank you very much for the awesome contribution! Just a couple of things:

1. Can you modify the commit messages so they fit our commit-style?
https://docs.teamhephy.com/contributing/submitting-a-pull-request/#commit-style

2. Can you rebase from master or merge in master on top of your branch so that Travis CI run?

Also, do you know of a good way that we can write a test to build slugs for all of these buildpacks and verify that they run correctly? Not sure if this is something we want to do as it will be a time consuming test but it might be good to run as an integration test every once in a while...

**Comment by duanhongyi** [comment]
OK, I try to upgrade to heroku-18 and submit it all together.

**Comment by Cryptophobia** [comment]
@duanhongyi , that would be great! Let me know if you need any assistance.

**Comment by kingdonb** [comment]
Actually, here this looks like the place: https://github.com/teamhephy/workflow-e2e/blob/master/tests/buildpacks_test.go

**Pull request closed without merging**
